spectacles-ci/spectacles

fonz/cli.py, fonz/tests/constants.py, fonz/tests/test_cli.py, requirements.txt, setup.py
This PR mainly adds testing coverage for `cli.py`. I'm using a few key concepts here:
1. `click` has a small testing library with a class called `CliRunner`. This is used to simulate an actual call from the command line with a list of options and arguments. I've set this up as a pytest fixture which is used by each test class (becomes a class attribute called `runner`).
2. I've mocked the `Fonz` class in a few places so we can test the mock using `assert_called_with` and ensure it's being instantiated correctly.
3. Implemented a hierarchy of `CLI > Environment Variable > Config` for option selection. I know we talked about the config file being a higher priority than environment variables, but it's difficult to set up that way with the way `click` works. Plus, I think it makes sense for …
=> CLI upgrades and testing

fonz/connection.py
Use a single session for all requests with stored, authenticated headers instead of calling the `requests` methods separately.
=> Use a requests Session object

spectacles/client.py, spectacles/utils.py
Include the `message` key from the response JSON, if found, in `APIConnectionError` messaging. Add a utility to pull that string out of the response object. Also add suggestion for branch checkout errors to ensure there are no uncommitted changes.
=> Improve error messaging for API errors

config.example.yml, spectacles/validators.py, tests/test_sql_validator.py
Workaround for an issue where the Looker API was returning query results with status `expired` when they should have been `running` or `error`. This workaround an `expired` query task like it's still running, which should be safe since all of these query tasks will have just been started.
Also adds more strict type checking around the Looker API response, which should raise exceptions for unexpected results rather than silently passing them.
=> Improve API error handling

spectacles/client.py, spectacles/validators.py, tests/test_sql_validator.py
=> Validate instance version before SQL validation

spectacles/cli.py
Closes #59.
This PR adds help messages for both the `sql` and `connect` commands. 
The output looks as follows:
```shell
dylan@Dylans-MacBook-Pro:spectacles-ci/spectacles ‹feature/help-messages*›$ spectacles sql -h
usage: spectacles sql [-h] [--config-file CONFIG_FILE] --base-url BASE_URL
--client-id CLIENT_ID --client-secret CLIENT_SECRET
[--port PORT] [--api-version API_VERSION] [-v] --project
PROJECT --branch BRANCH
[--explores EXPLORES [EXPLORES ...]] [--batch]
optional arguments:
-h, --help            show this help message and exit
--config-file CONFIG_FILE
The path to an optional YAML config file.
--base-url BASE_URL   The URL of your Looker instance, e.g. https://company-
name.looker.com
--client-id CLIENT_ID
The client ID of the Looker user that spectacles will
authenticate as. …
```
=> Adding help messages

spectacles/cli.py, spectacles/client.py, spectacles/exceptions.py, spectacles/printer.py, spectacles/runner.py, spectacles/validators.py
Adds a new validator with command `spectacles assert` to support running LookML/data tests via the API.
The following outstanding items need to be completed before this is ready for review:
Closes #62.
=> Add data testing validator

spectacles/validators.py
Fixes https://github.com/spectacles-ci/spectacles/issues/99
Honestly, a bit unfamiliar with the codebase, so feel free to re-implement how you'd like, but this did the trick for me locally.
=> Skip explores with no dimensions

spectacles/validators.py
Your circle builds are failing since 5cc653c189bee67dcf260c432a73b282be2de2ef
```
spectacles/validators.py:251:89: E501 line too long (89 > 88 characters)
```
This fixes it
https://circleci.com/gh/spectacles-ci/spectacles/301
=> Fix Flake8 error

spectacles/cli.py, spectacles/client.py, spectacles/runner.py
Closes #89 
@joshtemple Wanted to test out one implementation of this. As discussed, happy to go another route if preferred.
Adds a flag `--remote-reset` to the SQL validator which tells spectacles to reset the branch to the remote version after checking it out.
=> Add remote reset flag

spectacles/client.py, spectacles/validators.py, tests/test_sql_validator.py
If the version detected is less than the defined minimum, issue a warning noting the version being used is not supported rather than refusing to run at all. (maybe it should also warn that it may crash Looker?)
We are running an older version of Looker (6.16.x) and I wanted to see if it simply would not work at all or if we were able to at least gain some utility. To my surprise, it seems to work ok, I have not run into the 500 errors (#73) that led to #81, yet.
=> Be less restrictive with Looker version check

spectacles/client.py, tests/test_client.py
After the version check was removed it no longer prints the instance version, which I thought was at least as interesting as the API version so I added it to the logged connection string.
=> Include instance looker version in connect msg

.github/CODEOWNERS, spectacles/client.py, tests/test_client.py
We run `limit 0` queries in order to test the validity of the SQL Looker generates. On lots of warehouses, that processes no data and is very fast (BigQuery and Redshift, notably).
On Snowflake, it still processes a lot of data and there isn't an `EXPLAIN` functionality we can use right now. The proposed solution is to add a `1=2` filter to all queries, which does stop it from processing data.
=> Add always false filter to queries to improve speed (particularly on Snowflake)

spectacles/cli.py, spectacles/validators.py, tests/resources/response_models.json, tests/test_sql_validator.py
Updated to use slash rather than period because it's possible that model names may contain period characters.
This PR replaces #121
=> Use slash to delimit model/explore in filters

spectacles/validators.py, tests/test_sql_validator.py
We ran into an error with one explore which yielded a `sql_error_loc`, but did not contain a line reference:
```python
"errors": [
{
"message": "The PostgreSQL database encountered an error while running this query.",
"message_details": "ERROR: column <scrubbed> does not exist\n  Position: 3178",
"params": 'SELECT <scrubbed>',
"edit_url": None,
"error_pos": None,
"level": "error",
"sql_error_loc": {"character": 3178},
}
],
```
We encountered an error in one of our explores which only yielded a message:
```python
"errors": [
{
"message": 'Access filter field "scrubbed" on model "scrubbed" is unset for the current user.',
"message_details": None,
"params": None,
"edit_url": None,
"error_pos": None,
"fatal": True,
"level": "fatal",
"login_required_oauth_application_id": None,
}
],
```
=> Handle more error variations

spectacles/cli.py, spectacles/client.py, spectacles/runner.py, spectacles/validators.py, tests/test_cli.py, tests/test_sql_validator.py
Situation was that once we ran Spectacles on our Looker instance
with 128 explores in our model, it killed the instance in a way that
it stopped responding and eventually crashed. I've diagnosed that it
was merely the number of running queries at a time that caused it.
It scheduled pretty much all 128 queries immediately.
So this adds a flag --max-concurrency which you can use to tweak
and set how much load you want to put on your Looker instance.
I've tried our staging server with 10 and it works nicely and doesn't
crash anything.
Of the things I did:
- made the validate SQL function async and moved the loop code in the parent function
- got rid of creating an asyncio loop as I don’t believe you need it (get_event_loop creates it if one does not exist)
- when you specify max_concurrency …
=> Support max_concurrency for running Looker queries

spectacles/validators.py, tests/test_sql_validator.py
:man_facepalming: 
This was proposed to be fixed via #117, but an incomplete example in that PR led to an incomplete solution. This time I updated the example to use a snippet taken directly from the error that was logged.
Note that there is also no `sql` key in this error which is now handled as well.
=> Handle access filter error

spectacles/client.py, tests/test_client.py
If there are not, the logging statements are causing an index out of range exception to be thrown. (fixes #103)
=> Don't assume there are any dimensions

.circleci/config.yml, .gitignore, .pre-commit-config.yaml, requirements-dev.txt, requirements.txt, setup.cfg, spectacles/client.py, spectacles/exceptions.py, spectacles/lookml.py, spectacles/validators.py, tests/test_client.py, tests/test_sql_validator.py
This is a refactor to move to a synchronous approach for API requests. Based on limited testing, this does not increase the runtime of SQL validation but significantly decreases the complexity of the code for ease of maintenance and contribution.
=> Convert asynchronous requests to synchronous

spectacles/validators.py
=> Print concurrency at beginning of SQL validator

spectacles/cli.py, spectacles/printer.py, spectacles/runner.py, spectacles/validators.py
Closes #142.
Changes the Runner validation methods to return native objects (e.g. `spectacles.lookml.Project`) instead of lists of dictionaries.
@DylanBaker, the `validate_data_tests` method only returns a list of `DataTestError` currently because assertions are not directly associated with the LookML structure. I'm curious to know if we should still try and slot these into a Model instead of just returning a list of errors. It may be helpful to have the consistency of always returning a Project object.
This would allow us to break out the `build_project` call and run that at `Runner` instantiation instead of individually for each validator.
FYI, I'm going to leave Project serialization for a separate PR.
=> Return objects from runner methods, not dictionaries

spectacles/cli.py
I somehow missed out an argument when resolving conflicts on #172. It doesn't appear to have been caught by the tests. I'm going to review the testing in that area of the CLI, but wanted to merge in the fix more urgently.
=> [Hotfix] Fixed missing argument error in run_sql method

spectacles/validators.py
This error message prevents the user from receiving an unhelpful `IndexError` raised by `_select` if the Looker API doesn't return any models for their project.
This can happen if the user has created a model in a project but it has not been unconfigured.
=> Add error message when no project models are found

spectacles/cli.py
A bit of hack (subclasses a private argparse action), but allows the behavior we would like.
Can set `SPECTACLES_IMPORT_PROJECTS` to case-insensitive `True` or `False`, otherwise the `--import-projects` CLI flag works without an option being provided. Setting the option with a `true` or `false` in the YAML file still works as well.
=> Allow `store_true` action with environment variables

spectacles/cli.py, spectacles/logger.py, spectacles/validators.py, tests/test_cli.py, tests/test_logger.py
This PR introduces a few fixes:
- Moves `log_failing_sql` so it sits in `logger.py`, adds a separate test module for log testing, and prepends "Test SQL: " before the filename in the output so it's clear what the path is for.
- Fixes a bug where dimension queries were referencing their explores, not dimensions, effectively breaking single mode.
- Fixes another bug in cli.py where the dimension-level errors were not being printed in hybrid mode.
=> Fix bug not respecting single or hybrid mode

spectacles/cli.py, spectacles/lookml.py, tests/test_lookml.py
closes #132 
@joshtemple This PR adds a message at the end of errored batch runs to suggest they run in single or hybrid mode.
In order to figure out the plurals in the error message, I've added `number_of_errors` properties to the LookML objects. This could have been achieved with a count in the CLI, but I figured there is value in having those properties.
[examples below]
=> Add batch mode help message

requirements.txt, spectacles/cli.py, spectacles/tracking.py, tests/test_tracking.py
Wanted to create a draft of what tracking might look like. 
I settled on Segment because:
* GA and Heap don't seem to work well with exclusively server-side events
* Snowplow doesn't have a hosted free tier 
* Segment has pretty good free tier for startups with minimal funding
Ultimately, I think I'd like to use Snowplow, but this should be an easy way to get us going. 
I wanted to get eyes on a possible implementation before adding testing/etc. 
@joshtemple @Hawk94 You should have both received an invite to Segment.
=> Adding anonymised Segment tracking

spectacles/client.py, spectacles/runner.py, tests/cassettes/init_runner.yaml, tests/conftest.py, tests/test_client.py, tests/test_runner.py, tests/test_sql_validator.py
This PR gets rid of the `update_session` method and creates:
* `checkout_branch`
* `update_workspace`
* `reset_to_remote`
It updates the Runner accordingly.
closes #96
=> Make client methods have one-to-one relationship with API endpoints

spectacles/logger.py
Solves an issue with Unicode encoding errors in the `FileHandler` of the Spectacles logger.
=> Log with UTF-8 to file

spectacles/cli.py, spectacles/exceptions.py, spectacles/printer.py, spectacles/validators.py
We can generate a URL to the failing data test from what's returned in the API response. I need to test in more detail how this will handle folders before merging.
=> Add LookML url to assert outputs

spectacles/cli.py, spectacles/client.py, spectacles/runner.py, spectacles/select.py, spectacles/validators.py, tests/cassettes/test_data_test_validator/fixture_validator_fail.yaml, tests/cassettes/test_data_test_validator/fixture_validator_init.yaml, tests/test_cli.py, tests/test_data_test_validator.py, tests/test_select.py, tests/test_sql_validator.py
Closes #227, closes #165. Refactors the selection logic to use regex, making it much more concise and readable. Move the `--explores` and `--exclude` arguments to the validator subparser.
The architecture of this change means it's much more difficult to validate the selectors and exclusions passed in (for example, raising an error on `model_a/explore_c` to communicate that `explore_c` doesn't exist). This isn't ideal, because it's nice to catch when people have typos in their args, for example.
=> Allow model/explore selection and exclusion in assert

spectacles/cli.py, spectacles/client.py, spectacles/exceptions.py, spectacles/runner.py, spectacles/types.py, spectacles/validators/content.py, spectacles/validators/data_test.py, spectacles/validators/sql.py, spectacles/validators/validator.py, tests/cassettes/test_data_test_validator/fixture_validator_fail.yaml, tests/cassettes/test_data_test_validator/fixture_validator_init.yaml, tests/cassettes/test_data_test_validator/fixture_validator_pass.yaml, tests/test_cli.py, tests/test_data_test_validator.py, tests/test_lookml.py, tests/test_printer.py, tests/test_runner.py, tests/utils.py
Closes #238 
Accomplishes a few things:
- Moves the `build_project` method to the base validator
- Moves logging out of the data test validator and into the `Runner` or CLI module
- Applies selection using the standardized `is_selected` function (similar to the Content and SQL validators)
=> Refactor data test validator to use Project

spectacles/client.py
i had an older looker api entry in ~/.netrc which was causing me authentication headaches. this PR effectively ignores ~/.netrc entries for looker api. the official looker SDK does this as well https://github.com/looker-open-source/sdk-codegen/blob/master/python/looker_sdk/rtl/requests_transport.py#L77
=> fix: ignore ~/.netrc entries when authenticating to looker api

Dockerfile
I've recently come across spectacles and noticed it is not docker-ready to ease CI implementation. In my project, I have prepared a `Dockerfile` that allowed the `spectacles` command to be containerized and super easy to integrate into build pipelines like CircleCI's.
The next step from here would be to integrate this Dockefile into this repository's existing CircleCI pipeline to allow it to be tagged & pushed automatically to dockerhub.com, so spectacles would have its own official dockerhub image available  There's currently no official in dockerhub available, as seen [here](https://hub.docker.com/search?q=spectacles-ci&type=image). I'm not super familiar with publishing to dockerhub, so open to receive advice and feedback on this one :)
Considering this is not published to dockerhub …
=> Adds Dockerfile to allow independent execution and facilitate CI integrations

spectacles/client.py, spectacles/runner.py
60 minutes after authenticating the client, we need to re-authenticate with the Looker client. When we do so, the workspace gets reset to production, even if we had previously been in development mode. This change fixes that behaviour. If we were in development mode when the token expires, we will reset to development mode after re-authenticating.
Closes #392
=> Reset Client to development mode if required after 60 minute timeout

spectacles/client.py, spectacles/validators/sql.py
We find that the Looker API can semi-regularly provide transient errors. We already had some logic to retry after Timeout errors. This PR extends that retry to _all_ requests and now also retries after HTTPErrors.
Closes #379
=> Change retry to apply to all client requests + for HTTPError

spectacles/exceptions.py, spectacles/validators/content.py, tests/resources/validation_schema.json, tests/test_content_validator.py
When we raise a content validation error for a dashboard, it can be hard to know where the error is coming from in the dashboard as there can be many tiles and filters. This PR adds two new fields to the content validation error, one specifying whether it is a visualisation or filter, and another specifying the title of the visualisation or filter. This should make it easier to pinpoint where content validation errors are coming from. 
Closes #374
=> Add tile type and title to content validation errors

spectacles/lookml.py, spectacles/validators/data_test.py, tests/resources/validation_schema.json, tests/test_data_test_validator.py
We have had a request from a number of customers to return _all_ data tests, not just passing data tests. This PR achieves this by doing the following:
- Adds a `successes` key to the `Explore` class.
- Adds all passing data tests as JSON to the `successes` key on the explore.
- Formats the results for consumption by the hosted service
Closes #397
=> Add 'successes' to result of data test validator

spectacles/validators/content.py
Currently, even if a user don't ask to include specfic folders, exclude specific folders, or exclude personal folders, we still make multiple calls to the GET all folders endpoint. On some instances, that can be a very slow API call. This change fixes that behaviour.
> Closes #440
=> Skip all folders calls when not necessary

spectacles/client.py
Currently, all API calls have a 5 minute timeout. For some instances, the content validator can run for up to an hour. This PR extends the timeout for the content validation API call to one hour.
> Closes #450
=> Extend API call timeout to one hour for content validation

spectacles/validators/data_test.py
When a SQL error occurs during a data test, we don't attach the model name, explore name and test name to the error object because the JSON response from Looker is different. This PR makes a small change to fix this.
=> Attach model, explore and test names to data tests with SQL errors

spectacles/cli.py, spectacles/printer.py, tests/cassettes/init_client.yaml, tests/test_printer.py
In a previous change (#403), for content errors coming from dashboards, we added the tile type (tile or filter) and title to the error metadata. This change takes that information and prints it to the user.
For example,
```
============================= testing ============================
Tile 'Brand Share of Wallet over Customer Lifetime' failed validation.
Error in thelook/orders_with_share_of_wallet_application: Unknown field
"order_items.share_of_wallet_brand_within_company".
Dashboard: https://spectacles.looker.com/dashboards/9
Completed content validation in 2 seconds.
```
which shows that the problem is with a dashboard tile about Share of Wallet.
None.
=> Print tile type and title for content errors

spectacles/exceptions.py, spectacles/lookml.py, spectacles/runner.py, spectacles/validators/lookml.py
This change fixes an issue where the explore-level query would error but the dimension-level queries would pass, resulting in a run status inconsistent with error results.
This change adds some logic to the way results are retrieved from the project to return the explore-level errors if no dimension-level errors are found. However, this naive approach broke the way incremental errors are handled, since we couldn't differentiate between the incremental case and the problematic case.
So I've introduced a new attribute on the ValidationError class, `ignore`, which is used by incremental runs to tell the `get_results` method to skip those errors as duplicated.
Closes #512
=> Properly handle failed runs without dimension errors

spectacles/runner.py
Fixes the branch manager call we use for non-incremental runs to handle `--commit-ref` correctly.
Closes #522.
=> Handle ephemeral state correctly

spectacles/validators/sql.py
When extracting error details from Looker query results, we should log the query result if we're unable to parse it to assist with debugging.
In fact, we were already doing this, but for a too narrow scope of exception types. This expands the try/except to include all `Exception`, which will catch the `AttributeError` that we've been encountering.
Closes #525
=> Log for all exception encountered when parsing Looker query results

spectacles/runner.py, spectacles/validators/sql.py, tests/test_sql_validator.py
This change makes two fixes:
When we adjusted the profiler to account for incremental and query chunking, I assumed that users would want to see the profiler results printed out by test, rather than by query. It turns out this is not that useful, as users running the profiler are trying to debug long-running queries and don't really need to know what tests they're part of. Also, on non-fail-fast runs, we were performing profiling twice.
This change goes back to the old behavior of showing profile results at the query level, and removes the redundant profiling step when in non-fail-fast mode.
We were not using the correct query for compiling SQL and generating the Explore from Here URL for SQL tests. This caused unexpected results when in incremental mode for Explores with more than 500 …
=> Fix profiler and chunking issue

spectacles/client.py, spectacles/validators/sql.py, tests/test_utils.py
A nice medley of bugfixes...
1. No longer generate an extra `create_query` call to the Looker API when an explore has N dimensions < chunk size
2. Fix an issue where 2 explores in different models with the same name and same compiled SQL caused one explore to be queried in dimension mode regardless of SQL uniqueness
3. To be safe, we're comparing explores on the hash of their SQL + fully qualified name and not just name (e.g. `model/explore` instead of `explore`
=> Assorted fixes for 2.0.5

spectacles/cli.py, spectacles/runner.py, tests/cassettes/test_runner/test_incremental_sql_with_diff_explores_and_invalid_diff_sql_should_error.yaml, tests/cassettes/test_runner/test_incremental_sql_with_diff_explores_and_invalid_existing_sql_should_error.yaml, tests/cassettes/test_runner/test_incremental_sql_with_diff_explores_and_invalid_sql_should_error.yaml, tests/cassettes/test_runner/test_incremental_sql_with_diff_explores_and_valid_sql_should_not_error.yaml, tests/cassettes/test_runner/test_incremental_sql_with_equal_explores_should_not_error.yaml, tests/cassettes/test_runner/test_validate_content_should_work.yaml, tests/cassettes/test_runner/test_validate_data_tests_should_work.yaml, tests/cassettes/test_runner/test_validate_sql_should_work[False].yaml, tests/cassettes/test_runner/test_validate_sql_should_work[True].yaml, tests/test_cli.py
This PR updates the Runner, LookerBranchManager and CLI to allow users to run Spectacles with locally imported Looker projects pinned to specific git refs.
i.e. if the project `eye_exam` currently locally imports `welcome_to_looker`, the prior behaviour would have always tested `welcome_to_looker` @ production. Now, by passing the following CLI arg, we can test it at any git ref:
```bash
--pin-imports welcome_to_looker:some-branch-name
```
Closes #454
=>  Provide ability for users to pin locally imported projects to specific git refs

spectacles/cli.py, spectacles/lookml.py, spectacles/runner.py, tests/cassettes/test_lookml/TestBuildDimensions.test_dimension_count_should_match.yaml, tests/cassettes/test_lookml/TestBuildDimensions.test_hidden_dimension_should_be_excluded_with_ignore_hidden.yaml, tests/cassettes/test_lookml/TestBuildProject.test_duplicate_selectors_should_be_deduplicated.yaml, tests/cassettes/test_lookml/TestBuildProject.test_hidden_dimension_should_be_excluded_with_ignore_hidden.yaml, tests/cassettes/test_lookml/TestBuildProject.test_model_explore_dimension_counts_should_match.yaml, tests/conftest.py, tests/test_lookml.py
Testing hidden fields can be redundant. They can't be exposed to the user and if they are referenced in another dimension, the SQL will be tested as part of the SQL of the downstream field.
I should note, I don't suggest we ignore hidden fields by default. Sometimes users will temporarily unhide a field to add it to a report, and then re-hide the field. The field (and its SQL) are therefore still being used and we should test them by default.
Closes #163
=> Allow users to ignore hidden fields in SQL validation

spectacles/validators/sql.py
We are currently incorrectly logging the number of outstanding SQL tests to run. Currently, it logs the total number of tests, not the outstanding number of queries. This PR fixes this issue.
Hotfix, no issue
=> Fixing logging for outstanding query count in SQL validator

spectacles/client.py, tests/test_client.py
This changes allows handling for the `run_query` client function for when a 404 is returned. This can be because an explore or model doesn't exist on the branch and we need to return a string for incremental diff comparison.
Closes #554
=> Handle 404 when compiling SQL

spectacles/lookml.py, spectacles/runner.py, spectacles/validators/content.py, tests/test_content_validator.py
We currently prune the LookML tree when building the project. This means that content validator errors relating to explores that don't exist anymore don't get reported by Spectacles. This PR changes this functionality so that these errors now appear.
The changes work in the following way:
* When we build the project for content validation runs, we now return the entire LookML tree. This allows us to attach all errors to their relevant place on the tree, even if the explore has been excluded from the run. This is what allows us to distinguish between explores that have been deleted and explores that have been excluded by the filters.
* When we attach the errors to the LookML tree, we first check if the relevant explore exists. If it does, we attach the error there. We then check if the …
=> Report "dangling" content validator errors

spectacles/validators/content.py
Using spectacles on my company's Looker instance, I ran into error caused by (I think) the same issue as reported here: https://github.com/spectacles-ci/spectacles/issues/327
```
Encountered unexpected AttributeError: "'NoneType' object has no attribute 'get'"
```
The [PR to fix this issue](https://github.com/spectacles-ci/spectacles/pull/352) didn't seem to work in my case though, since the call to `content[content_type]["folder"]` returns a `None`, it's the `folder` that's not set, not the `id` attribute.
This change fixed the error for me locally.
Closes [#327](https://github.com/spectacles-ci/spectacles/issues/327)
=> Handle content errors without a folder

spectacles/lookml.py
There was a bug in the `build_project` function that meant Spectacles would only work with single model projects (or with projects where the model that was needed was the last one returned by the API, which was unlikely). 
This fix indents the loop that iterates over explores in the `build_project` function, ensuring that we include all relevant explores.
=> Fix indent in build_project explore loop

.gitignore, spectacles/client.py, tests/test_client.py
There was a call in the `run_lookml_test` function that was using `Session.get` instead of `self.get`. This PR fixes that and adds a test.
Closes #595
=> Update run_lookml_test to use proper request method 

spectacles/cli.py, spectacles/exceptions.py, spectacles/validators/content.py, tests/resources/validation_schema.json, tests/unit/test_content_validator.py
This change accounts for some deprecation that happened in the Looker API when going from v3.1 to 4.0. In the latest version, the key `space` has been replaced by `folder`.
**Important:** This change also expands allowed Content Validation errors from other types of content besides Looks and Dashboards (e.g. alerts or LookML dashboards). Previously we skipped content validation errors for non-Look or non-Dashboard content.
Description here
Closes #610, closes #600.
=> Fix issue with "space" deprecation

spectacles/client.py, spectacles/logger.py, spectacles/validators/sql.py, tests/unit/test_client.py, tests/unit/test_sql_validator.py
This change ensures that if the Looker API suddenly returns a bad response from the Create Async Query endpoint, Spectacles can handle the bad response without getting stuck in an infinite loop.
It increases the number of retries for HTTP status errors on Create Async Query from 3 -> 8.
It also forces the backoff library to log at the DEBUG level.
Closes #654
=> Improve how 502s from the Looker API are handled

spectacles/client.py
We were making an API call without authentication, which seems to work in almost all cases except for on some old versions of Looker. This PR updates the API call to fix the regression and make an authenticated request.
Closes #656
=> Add headers to Looker version API call

spectacles/validators/sql.py, tests/unit/test_sql_validator.py
Previously, when encountering an error in `SqlValidator._run_query`, we would wait for the running_queries queue to _clear_ but not for all tasks to be marked done. This didn't actually fix the error in #654, because any query still in an incomplete status (like running) would have left the running_queries queue but would not yet be marked done.
Now we call `.join()` which waits for all tasks from the queue to also be marked done.
Closes #654
=> Join instead of just waiting for empty queue

.pre-commit-config.yaml, spectacles/client.py
When we make requests to the LookML validation endpoint, we use the default Spectacles timeout of 300 seconds (5 minutes). This is too short for some instances with long validation times, so this change extends the timeout for that request to 30 minutes.
=> Extend timeout for LookML validation

spectacles/runner.py
This change resets `skip_imports` on the branch manager to an empty list, in the `__aexit__` function. This means that imports will be resolved for each use of the branch manager, which is the intended behaviour.
Closes #674
=> reset skip_imports when exiting branch manager

spectacles/runner.py, spectacles/validators/sql.py, tests/integration/test_runner.py, tests/unit/test_query.py
Fixes a bug where profiling did not work at all and expands profiling to be allowed for all queries again, not just fail fast queries.
It's important to note that the profiler results are a bit harder to interpret now that we use binary search. Previously, we had N + 1 queries for each Explore (one that selected all dimensions and one for each dimension). So a query either had exactly N dimensions or 1 dimension.
Now, a query can have any number of dimensions between 1 and N. I've basically handwaved this by returning "*" for the `Dimension(s)` column in the profiler output whenever a query has more than 1 dimension. It's worth documenting that this means "more than one" and not necessarily "all". I thought this was better than trying to print an arbitrarily long list of dimensions, but …
=> Fix profiling and open it back up to all queries

spectacles/client.py
Some customers are hitting LookML validation timeouts. The long running nature of this endpoint is due to issues with the Looker API that we have documented elsewhere. This change extends the Spectacles implemented timeout.
=> Extend LookML Validation timeout to 2 hours

spectacles/cli.py, spectacles/exceptions.py, spectacles/lookml.py, spectacles/printer.py, spectacles/runner.py, spectacles/types.py, spectacles/validators/sql.py, tests/resources/validation_schema.json, tests/unit/test_printer.py, tests/unit/test_sql_validator.py
This change modifies Spectacles SQL validation behavior from raising an exception on Explores with zero dimensions to instead logging a warning and marking the Explore as skipped.
Here's an example of the output. Note the warning log and the improvement in the "Testing" header, as well as `eye_exam.users__no_dims` being marked as `skipped` with a reason for skipping.
```bash
(spectacles) ➜ spectacles sql --project eye_exam --branch dev-josh-temple-8m75 --incremental
Connected to Looker version 23.6.53 using Looker API 4.0
Warning: Explore 'users__no_dims' does not have any non-ignored dimensions and will not be validated.
=================== Testing 2/5 explores [concurrency = 10] ====================
✓ eye_exam.users passed
✓ eye_exam.users__fail skipped (unmodified)
✓ …
```
=> Skip Explores without dimensions

spectacles/lookml.py, spectacles/types.py, spectacles/validators/sql.py, tests/unit/test_lookml.py, tests/unit/test_sql_validator.py
We've been encountering a new query status from Looker, `killed`. This was previously unhandled, so this change handles it by placing an error on the Explore indicating that testing for that Explore was interrupted.
=> Handle killed status for queries

spectacles/types.py, spectacles/validators/sql.py, tests/unit/test_sql_validator.py, tests/unit/test_types.py
This change allows a type of SQL validation error that we've been seeing following the release of the "new" LookML runtime. This type of error has an `error` key instead of `errors` and is string typed.
Now, instead of logging it and failing as unexpected, we can let this error flow through as a regular SQL validation error.
=> Allow Looker API errors with a single, string-typed error

poetry.lock, pyproject.toml, spectacles/tracking.py, tests/unit/test_tracking.py
When we updated away from a deprecated version of the Segment analytics package, a combination of lack of local environment leftovers + test coverage of the CLI tracking features + a bad configuration within the upstream package (see segmentio/analytics-python#325) meant that Spectacles was trying to find the old version but only had dependencies installed for the new version.
This change uses the correct import statement to use the new package.
Closes #760.
=> Fix Segment package import

pyproject.toml, spectacles/runner.py
Previously, we were not properly entering dev mode and respecting the `pin-imports` option when the run was set to run against Looker production. This change remedies that.
=> Ensure pin imports run go in dev mode

spectacles/cli.py, spectacles/runner.py, spectacles/validators/data_test.py
Add assert concurrency configuration
=> Add assert concurrency configuration

poetry.lock, pyproject.toml, spectacles/cli.py, spectacles/client.py, tests/unit/test_sql_validator.py
We were not backing off and retrying on manifest changes, which was by design since often the manifest is not there and we don't want to retry a 404. However, we can still retry timeouts, so I've added backoff for that endpoint for timeouts but not status errors.
We were not backing off and retrying on `httpx.ReadError`, so I've used the parent class `NetworkError` to catch this in our backoff logic.
We were only retrying most requests 3 times by default. With exponential backoff, this isn't waiting _that_ long in total. I've increased the number of retries to 10 for any network error or 502 status. I've ensured we give up immediately and don't retry on status error that isn't a 502.
=> Extend HTTP timeout

spectacles/client.py, tests/unit/test_client.py
Added `ReadTimeout` exception to the backoff retry mechanism in the Looker API client. This ensures that when HTTP read timeouts occur during API calls, the client will automatically retry the request using the existing exponential backoff strategy, improving reliability when dealing with slow or intermittent network connections.
[853](https://github.com/spectacles-ci/spectacles/issues/853)
=> Add read timeout handling with backoff and retry in Looker client
