spectacles-ci/spectacles

docs/join2019_submisson.md
Thought it might be easier to edit a file so moved [this issue](https://github.com/dbanalyticsco/Fonz/issues/3) across to this PR. 
(It's possible there is a way to convert the issue directly? I'm not super familiar with the workflow.)
=> Join 2019 Submission

.gitignore, spectacles/cli.py, spectacles/client.py, spectacles/validators.py
Also cleans up debug logging a bit.
=> Add verbose mode via CLI arg

spectacles/cli.py, spectacles/lookml.py, spectacles/runner.py, spectacles/validators.py, tests/test_sql_validator.py
=> Switch to query modes, add hybrid mode

spectacles/client.py
=> Add logic for using master branch

.circleci/config.yml, requirements.txt, spectacles/validators.py
=> Run black as part of the CircleCI process

spectacles/validators.py
Fixes https://github.com/spectacles-ci/spectacles/issues/100
=> Set line_number to None if key does not exist

spectacles/cli.py, spectacles/client.py, spectacles/validators.py, tests/test_sql_validator.py
=> Cancel running queries when Spectacles gets interrupted

setup.py, spectacles/cli.py, spectacles/logger.py
=> Allow users to specify logs location

README.md, codecov.yml
=> Updating Codecov settings and adding downloads badge

spectacles/lookml.py, spectacles/validators.py
This fixes the error described in #209 
Closes #209
=> add default to min() when evaluating results

requirements.txt, setup.py, spectacles/lookml.py, spectacles/runner.py, spectacles/types.py, spectacles/validators.py
=> Fix hybrid mode not returning dimensional errors

spectacles/cli.py, tests/test_cli.py
=> Specifically handle Looker API errors

spectacles/client.py, tests/test_client.py
=> Refresh Looker access token upon expiry

spectacles/runner.py
This is the open source fix for [this issue](https://github.com/spectacles-ci/spectacles-runner/issues/41). To push fix, we need to bump version and use new version in the runner.
=> Fix Manifest errors

spectacles/cli.py
=> Raise error if Python version requirement not met

spectacles/cli.py, spectacles/exceptions.py, tests/test_logger.py
=> Move SQL from test to metadata and remove test

spectacles/client.py, tests/test_client.py
=> Fix recursive loop on access token expiration

.circleci/config.yml, requirements-dev.txt, spectacles/select.py, spectacles/tracking.py, spectacles/utils.py
Run bandit on CI runs, plus a couple fixes to reach compliance.
=> Add bandit for security tests

spectacles/validators/content.py
=> Handle content errors without a folder ID

spectacles/validators/sql.py, tests/test_sql_validator.py
This PR excludes errors that match the Development Mode warning. The warning text has been changed in Looker version 7.12.
Closes #387
N/A
=> Account for new "Development Mode" warning text

spectacles/cli.py, spectacles/exceptions.py, spectacles/printer.py, spectacles/runner.py, spectacles/validators/lookml.py, tests/resources/validation_schema.json
- Updates JSON schema to include LookML validator response definition
- Adds `severity` argument for configuring
- Cosmetic changes to printing to make validator output match the other validators more closely
- Add line numbers to printed header to match IDE
N/A
=> Add-ons to LookML validation

spectacles/exceptions.py, spectacles/lookml.py, spectacles/runner.py, spectacles/validators/lookml.py
Previously a commit with the same message, 11f3c33c9c6aab331c1d85d01e562dad868eb860, was authored to be merged into `feature/chunk-queries`. This commit is the same change but slightly amended to work with v2.0.0rc1, rebased off of `master` and separated from the changes in `feature/chunk-queries`.
Description here
Closes #512
=> Properly handle failed runs without dimension errors (for v2.0.0)

spectacles/cli.py, spectacles/printer.py, spectacles/validators/lookml.py
Handle other LookML validator severity options from the Looker API like `fatal` and `success`.
Description here
=> Handle additional severity levels

spectacles/runner.py
Incremental Content Validation had a typo in the code. We were always building the results of the same project, instead of the project and target project. This PR resolves this typo.
Hotfix, no issue
=> Fix project -> target_project typo

spectacles/client.py, spectacles/runner.py
This change logs out the client ID, which should make it easier in concurrent contexts to debug which runs are tied to which users.
=> Log client ID for easier debugging of multi-user issues

spectacles/__init__.py, spectacles/lookml.py, spectacles/validators/sql.py
Fixes a bug where dimensions where not being built for certain explores because of bad list re-initialization in a loop.
=> Fix task creation bug

spectacles/client.py, tests/unit/test_client.py, tests/unit/test_sql_validator.py
Our backoff logic isn't working successfully on `HTTPStatusError`. This PR fixes this issue.
Closes #660
=> Fixing backoffs

spectacles/validators/sql.py, tests/unit/test_sql_validator.py
The Looker API returns the status `expired` for certain queries. However, sometimes it's a false alarm as the query eventually resolves itself to a completed status.
This change waits up to 30 seconds for that resolution to happen. If the query's status is still `expired` at that point, it puts the query back on the queue to be retried. After 2 retries it gives up and adds an error to the Explore.
Closes #111.
=> Wait for expired queries to resolve themselves or retry

poetry.lock, pyproject.toml
Pins the Segment analytics package to a former version that properly specifies its dependencies.
Closes #760.
=> Pin Segment analytics package

poetry.lock, pyproject.toml, spectacles/client.py
Looker changed the logic of the run_query endpoint when a dimension doesn't exist.
=> Account for new Looker logic in run_query endpoint

spectacles/client.py, spectacles/validators/sql.py, tests/unit/test_client.py
Add better error message for new run_query issues
=> Add better error message for new run_query issues

pyproject.toml, spectacles/client.py
After Looker changed their error code for the run_query endpoint, there is an error that we need to handle that we missed. This PR accounts for that.
=> Handle more run_query 400s

spectacles/client.py
Retry protocol errors for LookML Validation + clean up backoffs
=> Retry protocol errors for LookML Validation + clean up backoffs

pyproject.toml
=> Bump Spectacles version 2.4.9 -> 2.4.10

pyproject.toml, spectacles/cli.py, spectacles/printer.py
=> Add Looker CI Public Preview Announcement (b/428700588)

pyproject.toml
Bump Spectacles version 2.4.12 > 2.4.13
=> Bump Spectacles version 2.4.12 > 2.4.13
